import {
  Activity,
  Droplets,
  Gauge,
  Lightbulb,
  Music,
  Palette,
  Power,
  Radio,
  Sliders,
  Thermometer,
  Video,
  Zap,
} from "lucide-react";
import type { CapabilityDescriptor } from "@/models/capabilityDescriptor";
import { capabilityRegistry } from "./CapabilityRegistry";

const percent = (v: unknown) =>
  typeof v === "number" ? `${Math.round(v)} %` : "—";
const temp = (v: unknown, unit: string) =>
  typeof v === "number" ? `${v.toFixed(1)} °${unit}` : "—";

const BUILTINS: CapabilityDescriptor[] = [
  {
    id: "onOff",
    kind: "onOff",
    version: 1,
    name: "Power",
    description: "Ein-/Ausschalten",
    category: "general",
    dataType: "boolean",
    icon: Power,
    priority: 100,
    controlType: "power.toggle",
    altControlTypes: ["switch.glass", "readout.boolean"],
    format: (v) => (v ? "An" : "Aus"),
  },
  {
    id: "power",
    kind: "power",
    version: 1,
    name: "Ein / Aus",
    description: "Ein-/Ausschalten",
    category: "general",
    dataType: "boolean",
    icon: Power,
    priority: 98,
    controlType: "power.toggle",
    altControlTypes: ["switch.glass", "readout.boolean"],
    format: (v) => (v ? "An" : "Aus"),
  },
  {
    id: "dimmer",
    kind: "dimmer",
    version: 1,
    name: "Helligkeit",
    category: "lighting",
    dataType: "number",
    unit: "%",
    icon: Lightbulb,
    priority: 90,
    validation: { min: 0, max: 100, step: 1, precision: 0 },
    controlType: "slider.percentage",
    altControlTypes: ["stepper.numeric", "readout.progress"],
    format: percent,
  },
  {
    id: "rgb",
    kind: "rgb",
    version: 1,
    name: "Farbe",
    category: "lighting",
    dataType: "color",
    icon: Palette,
    priority: 80,
    controlType: "picker.color",
    altControlTypes: ["custom.generic"],
  },
  {
    id: "temperature",
    kind: "temperature",
    version: 1,
    name: "Temperatur",
    category: "climate",
    dataType: "number",
    unit: "°C",
    icon: Thermometer,
    priority: 90,
    validation: { min: 5, max: 35, step: 0.5, precision: 1 },
    controlType: "slider.temperature",
    altControlTypes: ["readout.number"],
    format: (v) => temp(v, "C"),
  },
  {
    id: "humidity",
    kind: "humidity",
    version: 1,
    name: "Luftfeuchtigkeit",
    category: "climate",
    dataType: "number",
    unit: "%",
    icon: Droplets,
    priority: 70,
    readOnly: true,
    validation: { min: 0, max: 100, step: 1, precision: 0 },
    controlType: "readout.progress",
    altControlTypes: ["readout.number"],
    format: percent,
  },
  {
    id: "position",
    kind: "position",
    version: 1,
    name: "Position",
    category: "general",
    dataType: "number",
    unit: "%",
    icon: Sliders,
    priority: 75,
    validation: { min: 0, max: 100, step: 1, precision: 0 },
    controlType: "slider.position",
    altControlTypes: ["slider.percentage", "readout.progress"],
    format: percent,
  },
  {
    id: "mode",
    kind: "mode",
    version: 1,
    name: "Modus",
    category: "general",
    dataType: "enum",
    icon: Activity,
    priority: 60,
    controlType: "segmented.enum",
    altControlTypes: ["dropdown.enum", "readout.enum"],
  },
  {
    id: "mediaTransport",
    kind: "mediaTransport",
    version: 1,
    name: "Wiedergabe",
    category: "media",
    dataType: "enum",
    icon: Music,
    priority: 90,
    controlType: "media.transport",
    altControlTypes: ["readout.status"],
  },
  {
    id: "stream",
    kind: "stream",
    version: 1,
    name: "Stream",
    category: "media",
    dataType: "boolean",
    icon: Video,
    priority: 70,
    readOnly: true,
    controlType: "readout.status",
  },
  {
    id: "energy",
    kind: "energy",
    version: 1,
    name: "Energie",
    category: "energy",
    dataType: "composite",
    unit: "W",
    icon: Zap,
    priority: 60,
    readOnly: true,
    controlType: "readout.energy",
    altControlTypes: ["readout.number"],
  },
  {
    id: "colorTemperature",
    kind: "colorTemperature",
    version: 1,
    name: "Farbtemperatur",
    category: "lighting",
    dataType: "number",
    unit: "K",
    icon: Lightbulb,
    priority: 70,
    validation: { min: 2000, max: 6500, step: 50, precision: 0 },
    controlType: "slider.color-temperature",
    altControlTypes: ["slider.percentage", "readout.number"],
    format: (v) => (typeof v === "number" ? `${Math.round(v)} K` : "—"),
  },
  {
    id: "fanSpeed",
    kind: "fanSpeed",
    version: 1,
    name: "Lüftergeschwindigkeit",
    category: "climate",
    dataType: "number",
    unit: "%",
    icon: Radio,
    priority: 65,
    validation: { min: 0, max: 100, step: 1, precision: 0 },
    controlType: "slider.percentage",
    altControlTypes: ["stepper.numeric", "readout.progress"],
    format: percent,
  },
  {
    id: "tilt",
    kind: "tilt",
    version: 1,
    name: "Neigung",
    category: "general",
    dataType: "number",
    unit: "%",
    icon: Sliders,
    priority: 55,
    validation: { min: 0, max: 100, step: 1, precision: 0 },
    controlType: "slider.tilt",
    altControlTypes: ["slider.percentage", "readout.progress"],
    format: percent,
  },
  {
    id: "volume",
    kind: "volume",
    version: 1,
    name: "Lautstärke",
    category: "media",
    dataType: "number",
    unit: "%",
    icon: Music,
    priority: 60,
    validation: { min: 0, max: 100, step: 1, precision: 0 },
    controlType: "slider.volume",
    altControlTypes: ["slider.percentage", "readout.progress"],
    format: percent,
  },
  {
    id: "mute",
    kind: "mute",
    version: 1,
    name: "Stumm",
    category: "media",
    dataType: "boolean",
    icon: Music,
    priority: 55,
    controlType: "toggle.mute",
    altControlTypes: ["power.toggle", "readout.boolean"],
  },
  {
    id: "seek",
    kind: "seek",
    version: 1,
    name: "Position",
    category: "media",
    dataType: "number",
    unit: "s",
    icon: Music,
    priority: 50,
    validation: { min: 0, max: 100, step: 1, precision: 0 },
    controlType: "slider.percentage",
    altControlTypes: ["readout.number"],
  },
  {
    id: "powerConsumption",
    kind: "powerConsumption",
    version: 1,
    name: "Leistung",
    category: "energy",
    dataType: "number",
    unit: "W",
    icon: Zap,
    priority: 65,
    readOnly: true,
    controlType: "readout.number",
    format: (v) => (typeof v === "number" ? `${v.toFixed(1)} W` : "—"),
  },
  {
    id: "voltage",
    kind: "voltage",
    version: 1,
    name: "Spannung",
    category: "energy",
    dataType: "number",
    unit: "V",
    icon: Zap,
    priority: 50,
    readOnly: true,
    controlType: "readout.number",
    format: (v) => (typeof v === "number" ? `${v.toFixed(1)} V` : "—"),
  },
  {
    id: "current",
    kind: "current",
    version: 1,
    name: "Strom",
    category: "energy",
    dataType: "number",
    unit: "A",
    icon: Zap,
    priority: 45,
    readOnly: true,
    controlType: "readout.number",
    format: (v) => (typeof v === "number" ? `${v.toFixed(2)} A` : "—"),
  },
  // Generic fallbacks for device.functions[] entries.
  {
    id: "boolean",
    kind: "boolean",
    version: 1,
    name: "Zustand",
    category: "general",
    dataType: "boolean",
    icon: Activity,
    priority: 30,
    controlType: "power.toggle",
    altControlTypes: ["readout.boolean"],
  },
  {
    id: "number",
    kind: "number",
    version: 1,
    name: "Wert",
    category: "general",
    dataType: "number",
    icon: Gauge,
    priority: 25,
    controlType: "stepper.numeric",
    altControlTypes: ["readout.number"],
  },
  {
    id: "text",
    kind: "text",
    version: 1,
    name: "Text",
    category: "general",
    dataType: "string",
    icon: Gauge,
    priority: 20,
    readOnly: true,
    controlType: "readout.text",
  },
  {
    id: "enum",
    kind: "enum",
    version: 1,
    name: "Auswahl",
    category: "general",
    dataType: "enum",
    icon: Activity,
    priority: 25,
    controlType: "segmented.enum",
    altControlTypes: ["dropdown.enum", "readout.enum"],
  },
  {
    id: "custom",
    kind: "custom",
    version: 1,
    name: "Eigenschaft",
    category: "custom",
    dataType: "composite",
    icon: Gauge,
    priority: 10,
    controlType: "custom.generic",
    altControlTypes: ["readout.text"],
  },
];

let bootstrapped = false;
export function bootstrapCapabilityRegistry(): void {
  if (bootstrapped) return;
  bootstrapped = true;
  for (const d of BUILTINS) capabilityRegistry.register(d);
}
