import {
  Activity,
  Droplets,
  Gauge,
  Lightbulb,
  Music,
  Palette,
  Power,
  Radio,
  Sliders,
  Thermometer,
  Video,
  Zap,
} from "lucide-react";
import type { CapabilityDescriptor } from "@/models/capabilityDescriptor";
import { capabilityRegistry } from "./CapabilityRegistry";

const percent = (v: unknown) =>
  typeof v === "number" ? `${Math.round(v)} %` : "—";
const temp = (v: unknown, unit: string) =>
  typeof v === "number" ? `${v.toFixed(1)} °${unit}` : "—";

const BUILTINS: CapabilityDescriptor[] = [
  {
    id: "onOff",
    kind: "onOff",
    version: 1,
    name: "Power",
    description: "Ein-/Ausschalten",
    category: "general",
    dataType: "boolean",
    icon: Power,
    priority: 100,
    controlType: "power.toggle",
    altControlTypes: ["switch.glass", "readout.boolean"],
    format: (v) => (v ? "An" : "Aus"),
  },
  {
    id: "dimmer",
    kind: "dimmer",
    version: 1,
    name: "Helligkeit",
    category: "lighting",
    dataType: "number",
    unit: "%",
    icon: Lightbulb,
    priority: 90,
    validation: { min: 0, max: 100, step: 1, precision: 0 },
    controlType: "slider.percentage",
    altControlTypes: ["stepper.numeric", "readout.progress"],
    format: percent,
  },
  {
    id: "rgb",
    kind: "rgb",
    version: 1,
    name: "Farbe",
    category: "lighting",
    dataType: "color",
    icon: Palette,
    priority: 80,
    controlType: "picker.color",
    altControlTypes: ["custom.generic"],
  },
  {
    id: "temperature",
    kind: "temperature",
    version: 1,
    name: "Temperatur",
    category: "climate",
    dataType: "number",
    unit: "°C",
    icon: Thermometer,
    priority: 90,
    validation: { min: 5, max: 35, step: 0.5, precision: 1 },
    controlType: "slider.temperature",
    altControlTypes: ["readout.number"],
    format: (v) => temp(v, "C"),
  },
  {
    id: "humidity",
    kind: "humidity",
    version: 1,
    name: "Luftfeuchtigkeit",
    category: "climate",
    dataType: "number",
    unit: "%",
    icon: Droplets,
    priority: 70,
    readOnly: true,
    validation: { min: 0, max: 100, step: 1, precision: 0 },
    controlType: "readout.progress",
    altControlTypes: ["readout.number"],
    format: percent,
  },
  {
    id: "position",
    kind: "position",
    version: 1,
    name: "Position",
    category: "general",
    dataType: "number",
    unit: "%",
    icon: Sliders,
    priority: 75,
    validation: { min: 0, max: 100, step: 1, precision: 0 },
    controlType: "slider.position",
    altControlTypes: ["slider.percentage", "readout.progress"],
    format: percent,
  },
  {
    id: "mode",
    kind: "mode",
    version: 1,
    name: "Modus",
    category: "general",
    dataType: "enum",
    icon: Activity,
    priority: 60,
    controlType: "segmented.enum",
    altControlTypes: ["dropdown.enum", "readout.enum"],
  },
  {
    id: "mediaTransport",
    kind: "mediaTransport",
    version: 1,
    name: "Wiedergabe",
    category: "media",
    dataType: "enum",
    icon: Music,
    priority: 90,
    controlType: "media.transport",
    altControlTypes: ["readout.status"],
  },
  {
    id: "stream",
    kind: "stream",
    version: 1,
    name: "Stream",
    category: "media",
    dataType: "boolean",
    icon: Video,
    priority: 70,
    readOnly: true,
    controlType: "readout.status",
  },
  {
    id: "energy",
    kind: "energy",
    version: 1,
    name: "Energie",
    category: "energy",
    dataType: "composite",
    unit: "W",
    icon: Zap,
    priority: 60,
    readOnly: true,
    controlType: "readout.energy",
    altControlTypes: ["readout.number"],
  },
  {
    id: "custom",
    kind: "custom",
    version: 1,
    name: "Eigenschaft",
    category: "custom",
    dataType: "composite",
    icon: Gauge,
    priority: 10,
    controlType: "custom.generic",
    altControlTypes: ["readout.text"],
  },
  // Radio placeholder to make lint happy for unused import removed below.
];

// avoid unused import warning
void Radio;

let bootstrapped = false;
export function bootstrapCapabilityRegistry(): void {
  if (bootstrapped) return;
  bootstrapped = true;
  for (const d of BUILTINS) capabilityRegistry.register(d);
}
