/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as AppRouteImport } from './routes/_app'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding.index'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as OnboardingWelcomeRouteImport } from './routes/onboarding.welcome'
import { Route as OnboardingServerRouteImport } from './routes/onboarding.server'
import { Route as OnboardingIntroRouteImport } from './routes/onboarding.intro'
import { Route as OnboardingDoneRouteImport } from './routes/onboarding.done'
import { Route as OnboardingConnectRouteImport } from './routes/onboarding.connect'
import { Route as OnboardingConfigureRouteImport } from './routes/onboarding.configure'
import { Route as AppTimelineRouteImport } from './routes/_app.timeline'
import { Route as AppStatisticsRouteImport } from './routes/_app.statistics'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppScenesRouteImport } from './routes/_app.scenes'
import { Route as AppRoomsRouteImport } from './routes/_app.rooms'
import { Route as AppMoreRouteImport } from './routes/_app.more'
import { Route as AppGroupsRouteImport } from './routes/_app.groups'
import { Route as AppDevicesRouteImport } from './routes/_app.devices'
import { Route as AppDashboardsRouteImport } from './routes/_app.dashboards'
import { Route as AppAutomationsRouteImport } from './routes/_app.automations'
import { Route as AppDashboardsIndexRouteImport } from './routes/_app.dashboards.index'
import { Route as AppSettingsUsersRouteImport } from './routes/_app.settings.users'
import { Route as AppSettingsServerRouteImport } from './routes/_app.settings.server'
import { Route as AppSettingsNotificationsRouteImport } from './routes/_app.settings.notifications'
import { Route as AppSettingsLanguageRouteImport } from './routes/_app.settings.language'
import { Route as AppSettingsDeveloperRouteImport } from './routes/_app.settings.developer'
import { Route as AppSettingsBackupRouteImport } from './routes/_app.settings.backup'
import { Route as AppSettingsAppearanceRouteImport } from './routes/_app.settings.appearance'
import { Route as AppScenesSceneIdRouteImport } from './routes/_app.scenes.$sceneId'
import { Route as AppRoomsRoomIdRouteImport } from './routes/_app.rooms.$roomId'
import { Route as AppGroupsGroupIdRouteImport } from './routes/_app.groups.$groupId'
import { Route as AppDevicesDeviceIdRouteImport } from './routes/_app.devices.$deviceId'
import { Route as AppDashboardsDashboardIdRouteImport } from './routes/_app.dashboards.$dashboardId'
import { Route as AppAutomationsNewRouteImport } from './routes/_app.automations.new'
import { Route as AppAutomationsAutomationIdRouteImport } from './routes/_app.automations.$automationId'
import { Route as AppDashboardsDashboardIdIndexRouteImport } from './routes/_app.dashboards.$dashboardId.index'
import { Route as AppSettingsServerNewRouteImport } from './routes/_app.settings.server.new'
import { Route as AppSettingsServerIdRouteImport } from './routes/_app.settings.server.$id'
import { Route as AppScenesSceneIdEditRouteImport } from './routes/_app.scenes.$sceneId.edit'
import { Route as AppDashboardsDashboardIdEditRouteImport } from './routes/_app.dashboards.$dashboardId.edit'
import { Route as AppAutomationsAutomationIdEditRouteImport } from './routes/_app.automations.$automationId.edit'

const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const OnboardingWelcomeRoute = OnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingServerRoute = OnboardingServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingIntroRoute = OnboardingIntroRouteImport.update({
  id: '/intro',
  path: '/intro',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingDoneRoute = OnboardingDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingConnectRoute = OnboardingConnectRouteImport.update({
  id: '/connect',
  path: '/connect',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingConfigureRoute = OnboardingConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => OnboardingRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppStatisticsRoute = AppStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppScenesRoute = AppScenesRouteImport.update({
  id: '/scenes',
  path: '/scenes',
  getParentRoute: () => AppRoute,
} as any)
const AppRoomsRoute = AppRoomsRouteImport.update({
  id: '/rooms',
  path: '/rooms',
  getParentRoute: () => AppRoute,
} as any)
const AppMoreRoute = AppMoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => AppRoute,
} as any)
const AppGroupsRoute = AppGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AppRoute,
} as any)
const AppDevicesRoute = AppDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsRoute = AppDashboardsRouteImport.update({
  id: '/dashboards',
  path: '/dashboards',
  getParentRoute: () => AppRoute,
} as any)
const AppAutomationsRoute = AppAutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardsIndexRoute = AppDashboardsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppDashboardsRoute,
} as any)
const AppSettingsUsersRoute = AppSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsServerRoute = AppSettingsServerRouteImport.update({
  id: '/server',
  path: '/server',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsNotificationsRoute =
  AppSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AppSettingsRoute,
  } as any)
const AppSettingsLanguageRoute = AppSettingsLanguageRouteImport.update({
  id: '/language',
  path: '/language',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsDeveloperRoute = AppSettingsDeveloperRouteImport.update({
  id: '/developer',
  path: '/developer',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsBackupRoute = AppSettingsBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRoute,
} as any)
const AppScenesSceneIdRoute = AppScenesSceneIdRouteImport.update({
  id: '/$sceneId',
  path: '/$sceneId',
  getParentRoute: () => AppScenesRoute,
} as any)
const AppRoomsRoomIdRoute = AppRoomsRoomIdRouteImport.update({
  id: '/$roomId',
  path: '/$roomId',
  getParentRoute: () => AppRoomsRoute,
} as any)
const AppGroupsGroupIdRoute = AppGroupsGroupIdRouteImport.update({
  id: '/$groupId',
  path: '/$groupId',
  getParentRoute: () => AppGroupsRoute,
} as any)
const AppDevicesDeviceIdRoute = AppDevicesDeviceIdRouteImport.update({
  id: '/$deviceId',
  path: '/$deviceId',
  getParentRoute: () => AppDevicesRoute,
} as any)
const AppDashboardsDashboardIdRoute =
  AppDashboardsDashboardIdRouteImport.update({
    id: '/$dashboardId',
    path: '/$dashboardId',
    getParentRoute: () => AppDashboardsRoute,
  } as any)
const AppAutomationsNewRoute = AppAutomationsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppAutomationsRoute,
} as any)
const AppAutomationsAutomationIdRoute =
  AppAutomationsAutomationIdRouteImport.update({
    id: '/$automationId',
    path: '/$automationId',
    getParentRoute: () => AppAutomationsRoute,
  } as any)
const AppDashboardsDashboardIdIndexRoute =
  AppDashboardsDashboardIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppDashboardsDashboardIdRoute,
  } as any)
const AppSettingsServerNewRoute = AppSettingsServerNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AppSettingsServerRoute,
} as any)
const AppSettingsServerIdRoute = AppSettingsServerIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppSettingsServerRoute,
} as any)
const AppScenesSceneIdEditRoute = AppScenesSceneIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AppScenesSceneIdRoute,
} as any)
const AppDashboardsDashboardIdEditRoute =
  AppDashboardsDashboardIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppDashboardsDashboardIdRoute,
  } as any)
const AppAutomationsAutomationIdEditRoute =
  AppAutomationsAutomationIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppAutomationsAutomationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/automations': typeof AppAutomationsRouteWithChildren
  '/dashboards': typeof AppDashboardsRouteWithChildren
  '/devices': typeof AppDevicesRouteWithChildren
  '/groups': typeof AppGroupsRouteWithChildren
  '/more': typeof AppMoreRoute
  '/rooms': typeof AppRoomsRouteWithChildren
  '/scenes': typeof AppScenesRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/statistics': typeof AppStatisticsRoute
  '/timeline': typeof AppTimelineRoute
  '/onboarding/configure': typeof OnboardingConfigureRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/intro': typeof OnboardingIntroRoute
  '/onboarding/server': typeof OnboardingServerRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/automations/$automationId': typeof AppAutomationsAutomationIdRouteWithChildren
  '/automations/new': typeof AppAutomationsNewRoute
  '/dashboards/$dashboardId': typeof AppDashboardsDashboardIdRouteWithChildren
  '/devices/$deviceId': typeof AppDevicesDeviceIdRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/rooms/$roomId': typeof AppRoomsRoomIdRoute
  '/scenes/$sceneId': typeof AppScenesSceneIdRouteWithChildren
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/backup': typeof AppSettingsBackupRoute
  '/settings/developer': typeof AppSettingsDeveloperRoute
  '/settings/language': typeof AppSettingsLanguageRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/server': typeof AppSettingsServerRouteWithChildren
  '/settings/users': typeof AppSettingsUsersRoute
  '/dashboards/': typeof AppDashboardsIndexRoute
  '/automations/$automationId/edit': typeof AppAutomationsAutomationIdEditRoute
  '/dashboards/$dashboardId/edit': typeof AppDashboardsDashboardIdEditRoute
  '/scenes/$sceneId/edit': typeof AppScenesSceneIdEditRoute
  '/settings/server/$id': typeof AppSettingsServerIdRoute
  '/settings/server/new': typeof AppSettingsServerNewRoute
  '/dashboards/$dashboardId/': typeof AppDashboardsDashboardIdIndexRoute
}
export interface FileRoutesByTo {
  '/automations': typeof AppAutomationsRouteWithChildren
  '/devices': typeof AppDevicesRouteWithChildren
  '/groups': typeof AppGroupsRouteWithChildren
  '/more': typeof AppMoreRoute
  '/rooms': typeof AppRoomsRouteWithChildren
  '/scenes': typeof AppScenesRouteWithChildren
  '/settings': typeof AppSettingsRouteWithChildren
  '/statistics': typeof AppStatisticsRoute
  '/timeline': typeof AppTimelineRoute
  '/onboarding/configure': typeof OnboardingConfigureRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/intro': typeof OnboardingIntroRoute
  '/onboarding/server': typeof OnboardingServerRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/': typeof AppIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/automations/$automationId': typeof AppAutomationsAutomationIdRouteWithChildren
  '/automations/new': typeof AppAutomationsNewRoute
  '/devices/$deviceId': typeof AppDevicesDeviceIdRoute
  '/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/rooms/$roomId': typeof AppRoomsRoomIdRoute
  '/scenes/$sceneId': typeof AppScenesSceneIdRouteWithChildren
  '/settings/appearance': typeof AppSettingsAppearanceRoute
  '/settings/backup': typeof AppSettingsBackupRoute
  '/settings/developer': typeof AppSettingsDeveloperRoute
  '/settings/language': typeof AppSettingsLanguageRoute
  '/settings/notifications': typeof AppSettingsNotificationsRoute
  '/settings/server': typeof AppSettingsServerRouteWithChildren
  '/settings/users': typeof AppSettingsUsersRoute
  '/dashboards': typeof AppDashboardsIndexRoute
  '/automations/$automationId/edit': typeof AppAutomationsAutomationIdEditRoute
  '/dashboards/$dashboardId/edit': typeof AppDashboardsDashboardIdEditRoute
  '/scenes/$sceneId/edit': typeof AppScenesSceneIdEditRoute
  '/settings/server/$id': typeof AppSettingsServerIdRoute
  '/settings/server/new': typeof AppSettingsServerNewRoute
  '/dashboards/$dashboardId': typeof AppDashboardsDashboardIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/onboarding': typeof OnboardingRouteWithChildren
  '/_app/automations': typeof AppAutomationsRouteWithChildren
  '/_app/dashboards': typeof AppDashboardsRouteWithChildren
  '/_app/devices': typeof AppDevicesRouteWithChildren
  '/_app/groups': typeof AppGroupsRouteWithChildren
  '/_app/more': typeof AppMoreRoute
  '/_app/rooms': typeof AppRoomsRouteWithChildren
  '/_app/scenes': typeof AppScenesRouteWithChildren
  '/_app/settings': typeof AppSettingsRouteWithChildren
  '/_app/statistics': typeof AppStatisticsRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/onboarding/configure': typeof OnboardingConfigureRoute
  '/onboarding/connect': typeof OnboardingConnectRoute
  '/onboarding/done': typeof OnboardingDoneRoute
  '/onboarding/intro': typeof OnboardingIntroRoute
  '/onboarding/server': typeof OnboardingServerRoute
  '/onboarding/welcome': typeof OnboardingWelcomeRoute
  '/_app/': typeof AppIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/_app/automations/$automationId': typeof AppAutomationsAutomationIdRouteWithChildren
  '/_app/automations/new': typeof AppAutomationsNewRoute
  '/_app/dashboards/$dashboardId': typeof AppDashboardsDashboardIdRouteWithChildren
  '/_app/devices/$deviceId': typeof AppDevicesDeviceIdRoute
  '/_app/groups/$groupId': typeof AppGroupsGroupIdRoute
  '/_app/rooms/$roomId': typeof AppRoomsRoomIdRoute
  '/_app/scenes/$sceneId': typeof AppScenesSceneIdRouteWithChildren
  '/_app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/_app/settings/backup': typeof AppSettingsBackupRoute
  '/_app/settings/developer': typeof AppSettingsDeveloperRoute
  '/_app/settings/language': typeof AppSettingsLanguageRoute
  '/_app/settings/notifications': typeof AppSettingsNotificationsRoute
  '/_app/settings/server': typeof AppSettingsServerRouteWithChildren
  '/_app/settings/users': typeof AppSettingsUsersRoute
  '/_app/dashboards/': typeof AppDashboardsIndexRoute
  '/_app/automations/$automationId/edit': typeof AppAutomationsAutomationIdEditRoute
  '/_app/dashboards/$dashboardId/edit': typeof AppDashboardsDashboardIdEditRoute
  '/_app/scenes/$sceneId/edit': typeof AppScenesSceneIdEditRoute
  '/_app/settings/server/$id': typeof AppSettingsServerIdRoute
  '/_app/settings/server/new': typeof AppSettingsServerNewRoute
  '/_app/dashboards/$dashboardId/': typeof AppDashboardsDashboardIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/automations'
    | '/dashboards'
    | '/devices'
    | '/groups'
    | '/more'
    | '/rooms'
    | '/scenes'
    | '/settings'
    | '/statistics'
    | '/timeline'
    | '/onboarding/configure'
    | '/onboarding/connect'
    | '/onboarding/done'
    | '/onboarding/intro'
    | '/onboarding/server'
    | '/onboarding/welcome'
    | '/onboarding/'
    | '/automations/$automationId'
    | '/automations/new'
    | '/dashboards/$dashboardId'
    | '/devices/$deviceId'
    | '/groups/$groupId'
    | '/rooms/$roomId'
    | '/scenes/$sceneId'
    | '/settings/appearance'
    | '/settings/backup'
    | '/settings/developer'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/server'
    | '/settings/users'
    | '/dashboards/'
    | '/automations/$automationId/edit'
    | '/dashboards/$dashboardId/edit'
    | '/scenes/$sceneId/edit'
    | '/settings/server/$id'
    | '/settings/server/new'
    | '/dashboards/$dashboardId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/automations'
    | '/devices'
    | '/groups'
    | '/more'
    | '/rooms'
    | '/scenes'
    | '/settings'
    | '/statistics'
    | '/timeline'
    | '/onboarding/configure'
    | '/onboarding/connect'
    | '/onboarding/done'
    | '/onboarding/intro'
    | '/onboarding/server'
    | '/onboarding/welcome'
    | '/'
    | '/onboarding'
    | '/automations/$automationId'
    | '/automations/new'
    | '/devices/$deviceId'
    | '/groups/$groupId'
    | '/rooms/$roomId'
    | '/scenes/$sceneId'
    | '/settings/appearance'
    | '/settings/backup'
    | '/settings/developer'
    | '/settings/language'
    | '/settings/notifications'
    | '/settings/server'
    | '/settings/users'
    | '/dashboards'
    | '/automations/$automationId/edit'
    | '/dashboards/$dashboardId/edit'
    | '/scenes/$sceneId/edit'
    | '/settings/server/$id'
    | '/settings/server/new'
    | '/dashboards/$dashboardId'
  id:
    | '__root__'
    | '/_app'
    | '/onboarding'
    | '/_app/automations'
    | '/_app/dashboards'
    | '/_app/devices'
    | '/_app/groups'
    | '/_app/more'
    | '/_app/rooms'
    | '/_app/scenes'
    | '/_app/settings'
    | '/_app/statistics'
    | '/_app/timeline'
    | '/onboarding/configure'
    | '/onboarding/connect'
    | '/onboarding/done'
    | '/onboarding/intro'
    | '/onboarding/server'
    | '/onboarding/welcome'
    | '/_app/'
    | '/onboarding/'
    | '/_app/automations/$automationId'
    | '/_app/automations/new'
    | '/_app/dashboards/$dashboardId'
    | '/_app/devices/$deviceId'
    | '/_app/groups/$groupId'
    | '/_app/rooms/$roomId'
    | '/_app/scenes/$sceneId'
    | '/_app/settings/appearance'
    | '/_app/settings/backup'
    | '/_app/settings/developer'
    | '/_app/settings/language'
    | '/_app/settings/notifications'
    | '/_app/settings/server'
    | '/_app/settings/users'
    | '/_app/dashboards/'
    | '/_app/automations/$automationId/edit'
    | '/_app/dashboards/$dashboardId/edit'
    | '/_app/scenes/$sceneId/edit'
    | '/_app/settings/server/$id'
    | '/_app/settings/server/new'
    | '/_app/dashboards/$dashboardId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  OnboardingRoute: typeof OnboardingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/onboarding/welcome': {
      id: '/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof OnboardingWelcomeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/server': {
      id: '/onboarding/server'
      path: '/server'
      fullPath: '/onboarding/server'
      preLoaderRoute: typeof OnboardingServerRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/intro': {
      id: '/onboarding/intro'
      path: '/intro'
      fullPath: '/onboarding/intro'
      preLoaderRoute: typeof OnboardingIntroRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/done': {
      id: '/onboarding/done'
      path: '/done'
      fullPath: '/onboarding/done'
      preLoaderRoute: typeof OnboardingDoneRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/connect': {
      id: '/onboarding/connect'
      path: '/connect'
      fullPath: '/onboarding/connect'
      preLoaderRoute: typeof OnboardingConnectRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/configure': {
      id: '/onboarding/configure'
      path: '/configure'
      fullPath: '/onboarding/configure'
      preLoaderRoute: typeof OnboardingConfigureRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/statistics': {
      id: '/_app/statistics'
      path: '/statistics'
      fullPath: '/statistics'
      preLoaderRoute: typeof AppStatisticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/scenes': {
      id: '/_app/scenes'
      path: '/scenes'
      fullPath: '/scenes'
      preLoaderRoute: typeof AppScenesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rooms': {
      id: '/_app/rooms'
      path: '/rooms'
      fullPath: '/rooms'
      preLoaderRoute: typeof AppRoomsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/more': {
      id: '/_app/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof AppMoreRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/groups': {
      id: '/_app/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AppGroupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/devices': {
      id: '/_app/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof AppDevicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards': {
      id: '/_app/dashboards'
      path: '/dashboards'
      fullPath: '/dashboards'
      preLoaderRoute: typeof AppDashboardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/automations': {
      id: '/_app/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AppAutomationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboards/': {
      id: '/_app/dashboards/'
      path: '/'
      fullPath: '/dashboards/'
      preLoaderRoute: typeof AppDashboardsIndexRouteImport
      parentRoute: typeof AppDashboardsRoute
    }
    '/_app/settings/users': {
      id: '/_app/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AppSettingsUsersRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/server': {
      id: '/_app/settings/server'
      path: '/server'
      fullPath: '/settings/server'
      preLoaderRoute: typeof AppSettingsServerRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/notifications': {
      id: '/_app/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AppSettingsNotificationsRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/language': {
      id: '/_app/settings/language'
      path: '/language'
      fullPath: '/settings/language'
      preLoaderRoute: typeof AppSettingsLanguageRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/developer': {
      id: '/_app/settings/developer'
      path: '/developer'
      fullPath: '/settings/developer'
      preLoaderRoute: typeof AppSettingsDeveloperRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/backup': {
      id: '/_app/settings/backup'
      path: '/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof AppSettingsBackupRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/settings/appearance': {
      id: '/_app/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRoute
    }
    '/_app/scenes/$sceneId': {
      id: '/_app/scenes/$sceneId'
      path: '/$sceneId'
      fullPath: '/scenes/$sceneId'
      preLoaderRoute: typeof AppScenesSceneIdRouteImport
      parentRoute: typeof AppScenesRoute
    }
    '/_app/rooms/$roomId': {
      id: '/_app/rooms/$roomId'
      path: '/$roomId'
      fullPath: '/rooms/$roomId'
      preLoaderRoute: typeof AppRoomsRoomIdRouteImport
      parentRoute: typeof AppRoomsRoute
    }
    '/_app/groups/$groupId': {
      id: '/_app/groups/$groupId'
      path: '/$groupId'
      fullPath: '/groups/$groupId'
      preLoaderRoute: typeof AppGroupsGroupIdRouteImport
      parentRoute: typeof AppGroupsRoute
    }
    '/_app/devices/$deviceId': {
      id: '/_app/devices/$deviceId'
      path: '/$deviceId'
      fullPath: '/devices/$deviceId'
      preLoaderRoute: typeof AppDevicesDeviceIdRouteImport
      parentRoute: typeof AppDevicesRoute
    }
    '/_app/dashboards/$dashboardId': {
      id: '/_app/dashboards/$dashboardId'
      path: '/$dashboardId'
      fullPath: '/dashboards/$dashboardId'
      preLoaderRoute: typeof AppDashboardsDashboardIdRouteImport
      parentRoute: typeof AppDashboardsRoute
    }
    '/_app/automations/new': {
      id: '/_app/automations/new'
      path: '/new'
      fullPath: '/automations/new'
      preLoaderRoute: typeof AppAutomationsNewRouteImport
      parentRoute: typeof AppAutomationsRoute
    }
    '/_app/automations/$automationId': {
      id: '/_app/automations/$automationId'
      path: '/$automationId'
      fullPath: '/automations/$automationId'
      preLoaderRoute: typeof AppAutomationsAutomationIdRouteImport
      parentRoute: typeof AppAutomationsRoute
    }
    '/_app/dashboards/$dashboardId/': {
      id: '/_app/dashboards/$dashboardId/'
      path: '/'
      fullPath: '/dashboards/$dashboardId/'
      preLoaderRoute: typeof AppDashboardsDashboardIdIndexRouteImport
      parentRoute: typeof AppDashboardsDashboardIdRoute
    }
    '/_app/settings/server/new': {
      id: '/_app/settings/server/new'
      path: '/new'
      fullPath: '/settings/server/new'
      preLoaderRoute: typeof AppSettingsServerNewRouteImport
      parentRoute: typeof AppSettingsServerRoute
    }
    '/_app/settings/server/$id': {
      id: '/_app/settings/server/$id'
      path: '/$id'
      fullPath: '/settings/server/$id'
      preLoaderRoute: typeof AppSettingsServerIdRouteImport
      parentRoute: typeof AppSettingsServerRoute
    }
    '/_app/scenes/$sceneId/edit': {
      id: '/_app/scenes/$sceneId/edit'
      path: '/edit'
      fullPath: '/scenes/$sceneId/edit'
      preLoaderRoute: typeof AppScenesSceneIdEditRouteImport
      parentRoute: typeof AppScenesSceneIdRoute
    }
    '/_app/dashboards/$dashboardId/edit': {
      id: '/_app/dashboards/$dashboardId/edit'
      path: '/edit'
      fullPath: '/dashboards/$dashboardId/edit'
      preLoaderRoute: typeof AppDashboardsDashboardIdEditRouteImport
      parentRoute: typeof AppDashboardsDashboardIdRoute
    }
    '/_app/automations/$automationId/edit': {
      id: '/_app/automations/$automationId/edit'
      path: '/edit'
      fullPath: '/automations/$automationId/edit'
      preLoaderRoute: typeof AppAutomationsAutomationIdEditRouteImport
      parentRoute: typeof AppAutomationsAutomationIdRoute
    }
  }
}

interface AppAutomationsAutomationIdRouteChildren {
  AppAutomationsAutomationIdEditRoute: typeof AppAutomationsAutomationIdEditRoute
}

const AppAutomationsAutomationIdRouteChildren: AppAutomationsAutomationIdRouteChildren =
  {
    AppAutomationsAutomationIdEditRoute: AppAutomationsAutomationIdEditRoute,
  }

const AppAutomationsAutomationIdRouteWithChildren =
  AppAutomationsAutomationIdRoute._addFileChildren(
    AppAutomationsAutomationIdRouteChildren,
  )

interface AppAutomationsRouteChildren {
  AppAutomationsAutomationIdRoute: typeof AppAutomationsAutomationIdRouteWithChildren
  AppAutomationsNewRoute: typeof AppAutomationsNewRoute
}

const AppAutomationsRouteChildren: AppAutomationsRouteChildren = {
  AppAutomationsAutomationIdRoute: AppAutomationsAutomationIdRouteWithChildren,
  AppAutomationsNewRoute: AppAutomationsNewRoute,
}

const AppAutomationsRouteWithChildren = AppAutomationsRoute._addFileChildren(
  AppAutomationsRouteChildren,
)

interface AppDashboardsDashboardIdRouteChildren {
  AppDashboardsDashboardIdEditRoute: typeof AppDashboardsDashboardIdEditRoute
  AppDashboardsDashboardIdIndexRoute: typeof AppDashboardsDashboardIdIndexRoute
}

const AppDashboardsDashboardIdRouteChildren: AppDashboardsDashboardIdRouteChildren =
  {
    AppDashboardsDashboardIdEditRoute: AppDashboardsDashboardIdEditRoute,
    AppDashboardsDashboardIdIndexRoute: AppDashboardsDashboardIdIndexRoute,
  }

const AppDashboardsDashboardIdRouteWithChildren =
  AppDashboardsDashboardIdRoute._addFileChildren(
    AppDashboardsDashboardIdRouteChildren,
  )

interface AppDashboardsRouteChildren {
  AppDashboardsDashboardIdRoute: typeof AppDashboardsDashboardIdRouteWithChildren
  AppDashboardsIndexRoute: typeof AppDashboardsIndexRoute
}

const AppDashboardsRouteChildren: AppDashboardsRouteChildren = {
  AppDashboardsDashboardIdRoute: AppDashboardsDashboardIdRouteWithChildren,
  AppDashboardsIndexRoute: AppDashboardsIndexRoute,
}

const AppDashboardsRouteWithChildren = AppDashboardsRoute._addFileChildren(
  AppDashboardsRouteChildren,
)

interface AppDevicesRouteChildren {
  AppDevicesDeviceIdRoute: typeof AppDevicesDeviceIdRoute
}

const AppDevicesRouteChildren: AppDevicesRouteChildren = {
  AppDevicesDeviceIdRoute: AppDevicesDeviceIdRoute,
}

const AppDevicesRouteWithChildren = AppDevicesRoute._addFileChildren(
  AppDevicesRouteChildren,
)

interface AppGroupsRouteChildren {
  AppGroupsGroupIdRoute: typeof AppGroupsGroupIdRoute
}

const AppGroupsRouteChildren: AppGroupsRouteChildren = {
  AppGroupsGroupIdRoute: AppGroupsGroupIdRoute,
}

const AppGroupsRouteWithChildren = AppGroupsRoute._addFileChildren(
  AppGroupsRouteChildren,
)

interface AppRoomsRouteChildren {
  AppRoomsRoomIdRoute: typeof AppRoomsRoomIdRoute
}

const AppRoomsRouteChildren: AppRoomsRouteChildren = {
  AppRoomsRoomIdRoute: AppRoomsRoomIdRoute,
}

const AppRoomsRouteWithChildren = AppRoomsRoute._addFileChildren(
  AppRoomsRouteChildren,
)

interface AppScenesSceneIdRouteChildren {
  AppScenesSceneIdEditRoute: typeof AppScenesSceneIdEditRoute
}

const AppScenesSceneIdRouteChildren: AppScenesSceneIdRouteChildren = {
  AppScenesSceneIdEditRoute: AppScenesSceneIdEditRoute,
}

const AppScenesSceneIdRouteWithChildren =
  AppScenesSceneIdRoute._addFileChildren(AppScenesSceneIdRouteChildren)

interface AppScenesRouteChildren {
  AppScenesSceneIdRoute: typeof AppScenesSceneIdRouteWithChildren
}

const AppScenesRouteChildren: AppScenesRouteChildren = {
  AppScenesSceneIdRoute: AppScenesSceneIdRouteWithChildren,
}

const AppScenesRouteWithChildren = AppScenesRoute._addFileChildren(
  AppScenesRouteChildren,
)

interface AppSettingsServerRouteChildren {
  AppSettingsServerIdRoute: typeof AppSettingsServerIdRoute
  AppSettingsServerNewRoute: typeof AppSettingsServerNewRoute
}

const AppSettingsServerRouteChildren: AppSettingsServerRouteChildren = {
  AppSettingsServerIdRoute: AppSettingsServerIdRoute,
  AppSettingsServerNewRoute: AppSettingsServerNewRoute,
}

const AppSettingsServerRouteWithChildren =
  AppSettingsServerRoute._addFileChildren(AppSettingsServerRouteChildren)

interface AppSettingsRouteChildren {
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsBackupRoute: typeof AppSettingsBackupRoute
  AppSettingsDeveloperRoute: typeof AppSettingsDeveloperRoute
  AppSettingsLanguageRoute: typeof AppSettingsLanguageRoute
  AppSettingsNotificationsRoute: typeof AppSettingsNotificationsRoute
  AppSettingsServerRoute: typeof AppSettingsServerRouteWithChildren
  AppSettingsUsersRoute: typeof AppSettingsUsersRoute
}

const AppSettingsRouteChildren: AppSettingsRouteChildren = {
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsBackupRoute: AppSettingsBackupRoute,
  AppSettingsDeveloperRoute: AppSettingsDeveloperRoute,
  AppSettingsLanguageRoute: AppSettingsLanguageRoute,
  AppSettingsNotificationsRoute: AppSettingsNotificationsRoute,
  AppSettingsServerRoute: AppSettingsServerRouteWithChildren,
  AppSettingsUsersRoute: AppSettingsUsersRoute,
}

const AppSettingsRouteWithChildren = AppSettingsRoute._addFileChildren(
  AppSettingsRouteChildren,
)

interface AppRouteChildren {
  AppAutomationsRoute: typeof AppAutomationsRouteWithChildren
  AppDashboardsRoute: typeof AppDashboardsRouteWithChildren
  AppDevicesRoute: typeof AppDevicesRouteWithChildren
  AppGroupsRoute: typeof AppGroupsRouteWithChildren
  AppMoreRoute: typeof AppMoreRoute
  AppRoomsRoute: typeof AppRoomsRouteWithChildren
  AppScenesRoute: typeof AppScenesRouteWithChildren
  AppSettingsRoute: typeof AppSettingsRouteWithChildren
  AppStatisticsRoute: typeof AppStatisticsRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAutomationsRoute: AppAutomationsRouteWithChildren,
  AppDashboardsRoute: AppDashboardsRouteWithChildren,
  AppDevicesRoute: AppDevicesRouteWithChildren,
  AppGroupsRoute: AppGroupsRouteWithChildren,
  AppMoreRoute: AppMoreRoute,
  AppRoomsRoute: AppRoomsRouteWithChildren,
  AppScenesRoute: AppScenesRouteWithChildren,
  AppSettingsRoute: AppSettingsRouteWithChildren,
  AppStatisticsRoute: AppStatisticsRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface OnboardingRouteChildren {
  OnboardingConfigureRoute: typeof OnboardingConfigureRoute
  OnboardingConnectRoute: typeof OnboardingConnectRoute
  OnboardingDoneRoute: typeof OnboardingDoneRoute
  OnboardingIntroRoute: typeof OnboardingIntroRoute
  OnboardingServerRoute: typeof OnboardingServerRoute
  OnboardingWelcomeRoute: typeof OnboardingWelcomeRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingConfigureRoute: OnboardingConfigureRoute,
  OnboardingConnectRoute: OnboardingConnectRoute,
  OnboardingDoneRoute: OnboardingDoneRoute,
  OnboardingIntroRoute: OnboardingIntroRoute,
  OnboardingServerRoute: OnboardingServerRoute,
  OnboardingWelcomeRoute: OnboardingWelcomeRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  OnboardingRoute: OnboardingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
